# Generated by Django 4.2.6 on 2024-03-13 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('culture', '0001_initial'),
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='study',
            options={'verbose_name': 'Студия', 'verbose_name_plural': 'Студии'},
        ),
    ]
