# Generated by Django 4.2.6 on 2024-03-15 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0002_student_weekday_studystartorder_actinvitestudy'),
        ('education', '0003_weekday_populate'),
    ]

    operations = [
    ]
