# Generated by Django 4.2.6 on 2024-03-13 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0003_teachereducation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teachereducation',
            options={'verbose_name': 'Преподаватель', 'verbose_name_plural': 'Преподаватели'},
        ),
    ]
