# Generated by Django 4.2.6 on 2024-03-15 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0003_weekday_populate'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherReport',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('education.teachereducation',),
        ),
        migrations.AlterModelOptions(
            name='studystartorder',
            options={'verbose_name': 'Приказ о работе студии', 'verbose_name_plural': 'Приказы о работе студии'},
        ),
        migrations.AlterModelOptions(
            name='weekday',
            options={'verbose_name': 'День недели', 'verbose_name_plural': 'Дни недели'},
        ),
    ]
