# Generated by Django 4.2.6 on 2024-03-15 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0004_teacherreport_alter_studystartorder_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbonementPriceSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Дата установки цены')),
                ('price_single', models.PositiveIntegerField(verbose_name='Цена (разовый абонимент)')),
                ('price_month', models.PositiveIntegerField(verbose_name='Цена (месячный абонимент)')),
                ('price_year', models.PositiveIntegerField(verbose_name='Цена (годовой абонимент)')),
                ('act_study_start_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.studystartorder', verbose_name='Приказ о работе студии')),
            ],
            options={
                'verbose_name': 'Установка цен на абонементы',
                'verbose_name_plural': 'Установка цен на абонементы',
            },
        ),
        migrations.DeleteModel(
            name='TeacherReport',
        ),
        migrations.CreateModel(
            name='StudyStartOrderReport',
            fields=[
            ],
            options={
                'verbose_name': 'Отчёты о преподаватеях',
                'verbose_name_plural': 'Отчёты о преподаватеях',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('education.studystartorder',),
        ),
    ]
