# Generated by Django 4.2.6 on 2024-03-15 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0005_abonementpriceset_delete_teacherreport_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbonementBuy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_buy', models.DateTimeField(verbose_name='Дата продажи')),
                ('type_abonement', models.CharField(choices=[('разовый', 'разовый'), ('месячный', 'месячный'), ('годовой', 'годовой')], max_length=255, verbose_name='Вид абонемента')),
                ('price', models.PositiveIntegerField(verbose_name='Цена')),
                ('act_invite_study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.actinvitestudy', verbose_name='Заявка на посещение студии')),
                ('start_order_study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.studystartorder', verbose_name='Приказ о работе студии')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.student', verbose_name='Студент')),
            ],
            options={
                'verbose_name': 'Продажа абонемента',
                'verbose_name_plural': 'Продажи абонементов',
            },
        ),
    ]
