# Generated by Django 4.2.6 on 2024-03-15 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0006_abonementbuy'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actinvitestudy',
            options={'verbose_name': 'Заявка на посещенте', 'verbose_name_plural': 'Заявки на посещение'},
        ),
    ]
