# Generated by Django 4.2.6 on 2023-10-10 18:06
import django
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Region",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regions.region', verbose_name='регион')),
            ],
            options={
                'verbose_name': 'Город РФ',
                'verbose_name_plural': 'Города РФ',
            },
        ),
    ]
