# Generated by Django 4.2.6 on 2023-10-10 19:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("regions", "0002_populate"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="region",
            options={
                "verbose_name": "Субъект РФ",
                "verbose_name_plural": "Субъекты РФ",
            },
        ),
        migrations.AlterField(
            model_name="region",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Название"),
        ),
    ]
