<<<<<<< HEAD
# Generated by Django 4.2.6 on 2024-03-13 17:11

from django.db import migrations, models
import django.db.models.deletion
=======
# Generated by Django 4.2.6 on 2024-03-13 17:09

from django.db import migrations, models
>>>>>>> c154d976cccbb3357e87581f08f670020eadd4db


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
        ('education', '0001_initial'),
=======
>>>>>>> c154d976cccbb3357e87581f08f670020eadd4db
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
            name='ArtifactOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_study', models.BooleanField()),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='education.study')),
            ],
            options={
                'verbose_name': 'Владелец экспоната',
                'verbose_name_plural': 'Владельцы экспоната',
            },
        ),
        migrations.CreateModel(
=======
>>>>>>> c154d976cccbb3357e87581f08f670020eadd4db
            name='Artifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
<<<<<<< HEAD
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='culture.artifactowner', verbose_name='Владелец')),
=======
            ],
            options={
                'verbose_name': 'Экспонат',
                'verbose_name_plural': 'Экспонаты',
            },
        ),
        migrations.CreateModel(
            name='ArtifactOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_study', models.BooleanField()),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
>>>>>>> c154d976cccbb3357e87581f08f670020eadd4db
            ],
            options={
                'verbose_name': 'Экспонат',
                'verbose_name_plural': 'Экспонаты',
            },
        ),
    ]
