# Generated by Django 4.2.6 on 2024-03-13 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0002_rename_studies_study_alter_study_options'),
        ('culture', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artifactowner',
            name='study',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='education.study'),
        ),
    ]
