# Generated by Django 4.2.6 on 2024-03-14 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0001_initial'),
        ('culture', '0002_foreignorganization_showcasetype_showcase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artifact',
            name='owner',
        ),
        migrations.AddField(
            model_name='artifact',
            name='owner_foreign_organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='culture.foreignorganization', verbose_name='Владелец (Сторонняя организация)'),
        ),
        migrations.AddField(
            model_name='artifact',
            name='owner_study',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='education.study', verbose_name='Владелец (Студия)'),
        ),
    ]
