# Generated by Django 4.2.6 on 2024-03-14 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entertainment', '0007_merge_20240314_1619'),
        ('culture', '0002_foreignorganization_showcasetype_showcase'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderExhibition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateRegister', models.DateTimeField(verbose_name='Приказ о проведении выставки')),
                ('dateStart', models.DateTimeField(verbose_name='Дата начала проведения')),
                ('dateEnd', models.DateTimeField(verbose_name='Дата окончания проведения')),
                ('artifacts', models.ManyToManyField(to='culture.artifact')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entertainment.place', verbose_name='Место проведения')),
                ('showcase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='culture.showcase', verbose_name='Выставка')),
            ],
            options={
                'verbose_name': 'Приказ о проведении выставки',
                'verbose_name_plural': 'Приказы о проведении выставок',
            },
        ),
    ]
