# Generated by Django 4.2.6 on 2024-03-14 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('culture', '0003_orderexhibition'),
        ('culture', '0003_remove_artifact_owner_and_more'),
    ]

    operations = [
    ]
