# Generated by Django 4.2.6 on 2024-03-14 16:59

from django.db import migrations, models
import django.db.models.deletion


def populate(apps, schema_editor):
    ShowcaseType = apps.get_model('culture', 'ShowcaseType')
    ShowcaseType.objects.create(name="Внутренняя")
    ShowcaseType.objects.create(name="Внешняя")


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0001_initial'),
        ('entertainment', '0008_merge_20240314_1643'),
        ('culture', '0004_merge_20240314_1643'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderExhibition',
            new_name='ShowcaseOrder',
        ),
        migrations.RenameField(
            model_name='showcaseorder',
            old_name='dateEnd',
            new_name='date_end',
        ),
        migrations.RenameField(
            model_name='showcaseorder',
            old_name='dateRegister',
            new_name='date_register',
        ),
        migrations.RenameField(
            model_name='showcaseorder',
            old_name='dateStart',
            new_name='date_start',
        ),
        migrations.AlterField(
            model_name='artifact',
            name='owner_foreign_organization',
            field=models.ForeignKey(blank=True, help_text='Выберите только одного владельца', null=True, on_delete=django.db.models.deletion.PROTECT, to='culture.foreignorganization', verbose_name='Владелец (Сторонняя организация)'),
        ),
        migrations.AlterField(
            model_name='artifact',
            name='owner_study',
            field=models.ForeignKey(blank=True, help_text='Выберите только одного владельца', null=True, on_delete=django.db.models.deletion.PROTECT, to='education.study', verbose_name='Владелец (Студия)'),
        ),
        migrations.CreateModel(
            name='ArtifactReturnAct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(verbose_name='Дата')),
                ('artifacts', models.ManyToManyField(to='culture.artifact', verbose_name='Экспонаты')),
                ('showcase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='culture.showcaseorder', verbose_name='Приказ о проведении выставки')),
            ],
            options={
                'verbose_name': 'Акт возврата экспонатов',
                'verbose_name_plural': 'Акты возврата экспонатов',
            },
        ),
        migrations.RunPython(populate, migrations.RunPython.noop)
    ]
