# Generated by Django 4.2.6 on 2024-03-14 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('capacity', models.IntegerField(verbose_name='Вместимость')),
                ('description', models.CharField(max_length=1000, verbose_name='Описание')),
                ('is_location', models.BooleanField(verbose_name='Имеются-ли локации')),
            ],
            options={
                'verbose_name': 'Место',
                'verbose_name_plural': 'Места',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rows', models.PositiveIntegerField(verbose_name='Количество рядов')),
                ('seats', models.PositiveIntegerField(verbose_name='Количество мест в ряду')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entertainment.place', verbose_name='Пространство')),
            ],
            options={
                'verbose_name': 'Локация',
                'verbose_name_plural': 'Локации',
            },
        ),
    ]
