# Generated by Django 4.2.6 on 2024-03-14 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата проведения')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('datetime_begin', models.DateTimeField(verbose_name='Время начала')),
                ('datetime_end', models.DateTimeField(verbose_name='Время окончания')),
                ('visitors_count', models.PositiveIntegerField(verbose_name='Количество поситителей')),
                ('is_paid', models.BooleanField(verbose_name='Платное мероприятие')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Мероприятие',
                'verbose_name_plural': 'Мероприятия',
            },
        ),
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=50, verbose_name='Тип мероприятия')),
            ],
            options={
                'verbose_name': 'Тип мероприятия',
                'verbose_name_plural': 'Типы мероприятий',
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('capacity', models.IntegerField(verbose_name='Вместимость')),
                ('description', models.CharField(max_length=1000, verbose_name='Описание')),
                ('is_location', models.BooleanField(verbose_name='Имеются-ли локации')),
            ],
            options={
                'verbose_name': 'Место',
                'verbose_name_plural': 'Места',
            },
        ),
        migrations.CreateModel(
            name='UnitPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.PositiveIntegerField(verbose_name='Ряд')),
                ('column', models.PositiveIntegerField(verbose_name='Место')),
                ('price', models.PositiveIntegerField(verbose_name='Стоимость')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entertainment.event', verbose_name='Мероприятие')),
            ],
            options={
                'verbose_name': 'Место',
                'verbose_name_plural': 'Места',
            },
        ),
        migrations.CreateModel(
            name='TicketPriceEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entertainment.event', verbose_name='Мероприятие')),
            ],
            options={
                'verbose_name': 'Установка цен на билеты',
                'verbose_name_plural': 'Установки цен на билеты',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название')),
                ('rows', models.PositiveIntegerField(verbose_name='Количество рядов')),
                ('seats', models.PositiveIntegerField(verbose_name='Количество мест в ряду')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entertainment.place', verbose_name='Пространство')),
            ],
            options={
                'verbose_name': 'Локация',
                'verbose_name_plural': 'Локации',
            },
        ),
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entertainment.eventtype', verbose_name='Тип'),
        ),
        migrations.AddField(
            model_name='event',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entertainment.place', verbose_name='Пространство'),
        ),
    ]
