<<<<<<< HEAD
# Generated by Django 4.2.6 on 2024-03-13 17:11
=======
# Generated by Django 4.2.6 on 2024-03-13 17:09
>>>>>>> c154d976cccbb3357e87581f08f670020eadd4db

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entertainment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='place',
            options={'verbose_name': 'Место', 'verbose_name_plural': 'Места'},
        ),
    ]
