# Generated by Django 4.2.6 on 2024-03-14 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entertainment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=50, verbose_name='Тип мероприятия')),
            ],
            options={
                'verbose_name': 'Тип мероприятия',
                'verbose_name_plural': 'Типы мероприятий',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата проведения')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('datetime_begin', models.DateTimeField(verbose_name='Время начала')),
                ('datetime_end', models.DateTimeField(verbose_name='Время окончания')),
                ('visitors_count', models.PositiveIntegerField(verbose_name='Количество поситителей')),
                ('is_paid', models.BooleanField(verbose_name='Платное мероприятие')),
                ('description', models.TextField(verbose_name='Описание')),
                ('event_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entertainment.eventtype', verbose_name='Тип')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entertainment.place', verbose_name='Пространство')),
            ],
            options={
                'verbose_name': 'Мероприятие',
                'verbose_name_plural': 'Мероприятия',
            },
        ),
    ]
