# Generated by Django 4.2.6 on 2024-03-14 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entertainment', '0003_FILL'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='place',
            options={'verbose_name': 'Пространство', 'verbose_name_plural': 'Пространства'},
        ),
    ]
