# Generated by Django 4.2.6 on 2024-03-14 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entertainment', '0004_alter_place_options'),
        ('entertainment', '0004_alter_place_options_unitplacepurchase'),
    ]

    operations = [
    ]
