# Generated by Django 4.2.6 on 2024-03-14 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entertainment', '0005_alter_unitplace_column_alter_unitplace_row'),
        ('entertainment', '0005_merge_20240314_1316'),
    ]

    operations = [
    ]
