# Generated by Django 4.2.6 on 2024-03-14 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entertainment', '0006_merge_20240314_1349'),
        ('entertainment', '0006_merge_20240314_1609'),
    ]

    operations = [
    ]
