# Generated by Django 4.2.6 on 2024-03-14 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entertainment', '0007_merge_20240314_1619'),
        ('entertainment', '0007_merge_20240314_1635'),
    ]

    operations = [
    ]
