# Generated by Django 4.2.6 on 2023-10-10 19:27

from django.db import migrations, models
import django.db.models.deletion


def generate_superuser(apps, schema_editor):
    from django.contrib.auth import get_user_model

    USERNAME = "admin"
    PASSWORD = "admin"
    EMAIL = None

    user = get_user_model()

    if not user.objects.filter(username=USERNAME, email=EMAIL).exists():
        admin = user.objects.create_superuser(
           username=USERNAME, password=PASSWORD, email=EMAIL
        )
        admin.save()



class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.RunPython(generate_superuser, migrations.RunPython.noop),
    ]
