# Generated by Django 4.2.11 on 2024-03-12 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_author_name_alter_book_author_alter_book_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='price',
            field=models.PositiveBigIntegerField(blank=True, default=0, null=True),
        ),
    ]
